### PR TITLE
Fix: issue with listing results displaying numbers that don't exist more in the order meta

### LINKED ISSUE #21: When document is deleted, still showing in the list
When a document is deleted, for example from the order page, only the order meta data is actually deleted. The number tools plugin queries the database numbers tables, which can retain deleted numbers, leading to issues in the results being displayed.

### PR DESCRIPTION
**Pull request by alexmigf**
closes #21

### CODE REVIEW

File: number-store-list-table.php [hunk 1]
```diff
@@ -211,30 +211,41 @@ public function get_search() {
...
+				$results = $wpdb->get_results( $wpdb->prepare( "SELECT * FROM $table_name ORDER BY $orderby $order LIMIT %d OFFSET %d", $this->per_page, $offset ) );
 			}
 		} else {
-			$results = 0;
+			$results = array();
+		}
+		
+		// remove db document numbers that don't exist more in the orders meta (documents were deleted)
+		if ( ! empty( $results ) && ! empty( $table_name ) ) {
+			$document_type = str_replace( 'wp_wcpdf_', '', $table_name );
```
Comment (MohamadNateqi) [inline number-store-list-table.php:234]: The prefix for the tables may be different from `wp_`.

**Review by MohamadNateqi — APPROVED** [review]
LGTM!
